<?php

namespace Database\Seeders;

use App\Models\Content;
use Illuminate\Database\Seeder;

class ContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        Content::create([
            'category_id' => 1,
            'owner_id'  => 1,
            'type_id' => 3,
            'title' => 'Popular 1',
            'short_des' => 'Popular 1',
            'image' => 'upload/content/image/2023_06_12_16_12_55_img-8.jpg',
            'banner_image' => 'upload/content/banner_image/2023_06_12_16_12_55_image-01.jpg',
            'description' => 'Popular 1',
            'artist_name' => 'Popular 1',
            'price' => 122,
            'file_name' => 'upload/content/file/2023_06_12_16_12_55_img-8.jpg',
            'file_size' => '45735',
            'location' => '12',
            'insert_date' => '2023-06-12 16:31:15',
            'update_date' => '2023-06-12 16:31:15',
            'approve_date' => NULL,
            'mapping_status' => 'active',
            'owner_status' => 'active',
            'status' => 'active',
            'created_by' => "admin",
            'insert_date' => date('Y-m-d H:i:s'),
        ]);

        Content::create([
            'category_id' => 1,
            'owner_id'  => 1,
            'type_id' => 3,
            'title' => 'Popular 2',
            'short_des' => 'Popular 2',
            'image' => 'upload/content/image/2023_06_12_16_18_17_img-3.jpg',
            'banner_image' => 'upload/content/banner_image/2023_06_12_16_18_17_img-6.jpg',
            'description' => 'Popular 2',
            'artist_name' => 'Popular 2',
            'price' => 1212,
            'file_name' => 'upload/content/file/2023_06_12_16_18_17_img-3.jpg',
            'file_size' => '122827',
            'location' => 'Popular 2',
            'insert_date' => '2023-06-12 16:18:17',
            'update_date' => '2023-06-12 16:18:17',
            'approve_date' => NULL,
            'mapping_status' => 'active',
            'owner_status' => 'active',
            'status' => 'active',
            'created_by' => "admin",
            'insert_date' => date('Y-m-d H:i:s'),
        ]);

        Content::create([
            'category_id' => 2,
            'owner_id'  => 2,
            'type_id' => 1,
            'title' => 'New 1',
            'short_des' => 'New 1',
            'image' => 'upload/content/image/2023_06_12_16_18_48_image-01.jpg',
            'banner_image' => 'upload/content/banner_image/2023_06_12_16_18_48_img-1.jpg',
            'description' => 'New 1',
            'artist_name' => 'New 1',
            'price' => 12,
            'file_name' => 'upload/content/file/2023_06_12_16_18_48_2023_06_12_13_58_31_video.mp4',
            'file_size' => '7729699',
            'location' => 'New 1',
            'insert_date' => '2023-06-12 16:18:48',
            'update_date' => '2023-06-12 16:18:48',
            'approve_date' => NULL,
            'mapping_status' => 'active',
            'owner_status' => 'active',
            'status' => 'active',
            'created_by' => "admin",
            'insert_date' => date('Y-m-d H:i:s'),
        ]);

        Content::create([
            'category_id' => 2,
            'owner_id'  => 2,
            'type_id' => 1,
            'title' => 'New 2',
            'short_des' => 'New 2',
            'image' => 'upload/content/image/2023_06_12_16_19_17_img-3.jpg',
            'banner_image' => 'upload/content/banner_image/2023_06_12_16_19_17_img-6.jpg',
            'description' => 'New 2',
            'artist_name' => 'New 2',
            'price' => 1212,
            'file_name' => 'upload/content/file/2023_06_12_16_19_17_slide-2.jpg',
            'file_size' => '122827',
            'location' => 'New 2',
            'insert_date' => '2023-06-12 16:19:17',
            'update_date' => '2023-06-12 16:19:17',
            'approve_date' => NULL,
            'mapping_status' => 'active',
            'owner_status' => 'active',
            'status' => 'active',
            'created_by' => "admin",
            'insert_date' => date('Y-m-d H:i:s'),
        ]);

        Content::create([
            'category_id' => 3,
            'owner_id'  => 2,
            'type_id' => 2,
            'title' => 'Trending 1',
            'short_des' => 'Trending 1',
            'image' => 'upload/content/image/2023_06_12_16_19_47_img-8.jpg',
            'banner_image' => 'upload/content/banner_image/2023_06_12_16_19_47_img-1.jpg',
            'description' => 'Trending 1',
            'artist_name' => 'Trending 1',
            'price' => 122,
            'file_name' => 'upload/content/file/2023_06_12_16_19_47_img-8.jpg',
            'file_size' => '45735',
            'location' => 'Trending 1',
            'insert_date' => '2023-06-12 16:19:47',
            'update_date' => '2023-06-12 16:19:47',
            'approve_date' => NULL,
            'mapping_status' => 'active',
            'owner_status' => 'active',
            'status' => 'active',
            'created_by' => "admin",
            'insert_date' => date('Y-m-d H:i:s'),
        ]);

        Content::create([
            'category_id' => 3,
            'owner_id'  => 2,
            'type_id' => 2,
            'title' => 'Trending 2',
            'short_des' => 'Trending 2',
            'image' => 'upload/content/image/2023_06_12_16_20_17_img-3.jpg',
            'banner_image' => 'upload/content/banner_image/2023_06_12_16_20_17_img-6.jpg',
            'description' => 'Trending 2',
            'artist_name' => 'Trending 2',
            'price' => 1212,
            'file_name' => 'upload/content/file/2023_06_12_16_20_17_slide-2.jpg',
            'file_size' => '122827',
            'location' => 'Trending 2',
            'insert_date' => '2023-06-12 16:20:17',
            'update_date' => '2023-06-12 16:20:17',
            'approve_date' => NULL,
            'mapping_status' => 'active',
            'owner_status' => 'active',
            'status' => 'active',
            'created_by' => "admin",
            'insert_date' => date('Y-m-d H:i:s'),
        ]);

        Content::create([
            'category_id' => 2,
            'owner_id'  => 1,
            'type_id' => 3,
            'title' => 'Popular 1',
            'short_des' => 'Popular 1',
            'image' => 'upload/content/image/2023_06_12_16_20_47_img-8.jpg',
            'banner_image' => 'upload/content/banner_image/2023_06_12_16_20_47_img-1.jpg',
            'description' => 'Popular 1',
            'artist_name' => 'Popular 1',
            'price' => 122,
            'file_name' => 'upload/content/file/2023_06_12_16_20_47_img-8.jpg',
            'file_size' => '45735',
            'location' => 'Popular 1',
            'insert_date' => '2023-06-12 16:20:47',
            'update_date' => '2023-06-12 16:20:47',
            'approve_date' => NULL,
            'mapping_status' => 'active',
            'owner_status' => 'active',
            'status' => 'active',
            'created_by' => "admin",
            'insert_date' => date('Y-m-d H:i:s'),
        ]);

        Content::create([
            'category_id' => 2,
            'owner_id'  => 1,
            'type_id' => 3,
            'title' => 'Popular 2',
            'short_des' => 'Popular 2',
            'image' => 'upload/content/image/2023_06_12_16_21_17_img-3.jpg',
            'banner_image' => 'upload/content/banner_image/2023_06_12_16_21_17_img-6.jpg',
            'description' => 'Popular 2',
            'artist_name' => 'Popular 2',
            'price' => 1212,
            'file_name' => 'upload/content/file/2023_06_12_16_21_17_slide-2.jpg',
            'file_size' => '122827',
            'location' => 'Popular 2',
            'insert_date' => '2023-06-12 16:21:17',
            'update_date' => '2023-06-12 16:21:17',
            'approve_date' => NULL,
            'mapping_status' => 'active',
            'owner_status' => 'active',
            'status' => 'active',
            'created_by' => "admin",
            'insert_date' => date('Y-m-d H:i:s'),
        ]);

        Content::create([
            'category_id' => 3,
            'owner_id'  => 2,
            'type_id' => 2,
            'title' => 'New 1',
            'short_des' => 'New 1',
            'image' => 'upload/content/image/2023_06_12_16_21_47_img-8.jpg',
            'banner_image' => 'upload/content/banner_image/2023_06_12_16_21_47_img-1.jpg',
            'description' => 'New 1',
            'artist_name' => 'New 1',
            'price' => 122,
            'file_name' => 'upload/content/file/2023_06_12_16_21_47_img-8.jpg',
            'file_size' => '45735',
            'location' => 'New 1',
            'insert_date' => '2023-06-12 16:21:47',
            'update_date' => '2023-06-12 16:21:47',
            'approve_date' => NULL,
            'mapping_status' => 'active',
            'owner_status' => 'active',
            'status' => 'active',
            'created_by' => "admin",
            'insert_date' => date('Y-m-d H:i:s'),
        ]);

        Content::create([
            'category_id' => 1,
            'owner_id'  => 3,
            'type_id' => 3,
            'title' => 'New 2',
            'short_des' => 'New 2',
            'image' => 'upload/content/image/2023_06_12_16_22_17_img-3.jpg',
            'banner_image' => 'upload/content/banner_image/2023_06_12_16_22_17_img-6.jpg',
            'description' => 'New 2',
            'artist_name' => 'New 2',
            'price' => 1212,
            'file_name' => 'upload/content/file/2023_06_12_16_22_17_slide-2.jpg',
            'file_size' => '122827',
            'location' => 'New 2',
            'insert_date' => '2023-06-12 16:22:17',
            'update_date' => '2023-06-12 16:22:17',
            'approve_date' => NULL,
            'mapping_status' => 'active',
            'owner_status' => 'active',
            'status' => 'active',
            'created_by' => "admin",
            'insert_date' => date('Y-m-d H:i:s'),
        ]);

        Content::create([
            'category_id' => 2,
            'owner_id'  => 1,
            'type_id' => 2,
            'title' => 'Trending 1',
            'short_des' => 'Trending 1',
            'image' => 'upload/content/image/2023_06_12_16_22_47_img-8.jpg',
            'banner_image' => 'upload/content/banner_image/2023_06_12_16_22_47_img-1.jpg',
            'description' => 'Trending 1',
            'artist_name' => 'Trending 1',
            'price' => 122,
            'file_name' => 'upload/content/file/2023_06_12_16_22_47_img-8.jpg',
            'file_size' => '45735',
            'location' => 'Trending 1',
            'insert_date' => '2023-06-12 16:22:47',
            'update_date' => '2023-06-12 16:22:47',
            'approve_date' => NULL,
            'mapping_status' => 'active',
            'owner_status' => 'active',
            'status' => 'active',
            'created_by' => "admin",
            'insert_date' => date('Y-m-d H:i:s'),
        ]);
    }
}
